spring:
  datasource:
    url: jdbc:h2:mem:coderhouse
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database:
      platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: joselopez11c@gmail.com
    password: czvkrdgvadntevgj
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

twilio:
  number-sms: '+18445370610'
  number-whatsapp: '+14155238886'
  account:
    sid: AC02a3e3befc4901b7c8b8042ad2dde8f7
  auth:
    token: a23b0ab9f865d6910e63bcbfb4e7da0a


springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /openapi/index.html
server:
  port: 8080